### ISSUE TITLE
Missing (or extra) fields from backend in frontend

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/credere-frontend#124]
Missing:

* ~~repaymentTermsSchema is missing annual_revenue. Or, ApplicationSelectCreditProduct in the backend shouldn't have annual_revenue. One or the other.~~ Was looking at old code.
* [ ] CreditProductBase.borrower_types was added in open-contracting/credere-backend@8c58d7a2d4929724c2a5ac813eeadc22fd900279 but `ICreditProductBase` was not updated.

Notes:

* ICreditProduct has `created_at?` and `updated_at?` with question marks. These will be null in the context where they match `CreditProductWithLender(CreditProductBase)` in the backend, which doesn't have timestamps. They will be populated when used under `IApplicationResponse`, which matches `CreditProduct` in the backend.

**Comment by yolile** [comment]
>  repaymentTermsSchema is missing annual_revenue. Or, ApplicationSelectCreditProduct in the backend shouldn't have annual_revenue. One or the other.

But we use:

`export type SelectCreditProductInput = CreditOptionsInput & Partial<RepaymentTermsInput> & { credit_product_id: number };`

So there is no need to put `annual_revenue` in  `repaymentTermsSchema`

**Comment by jpmckinney** [comment]
Nevermind - I hadn't pulled its addition to `creditOptionsSchema`

**Comment by yolile** [comment]
> CreditProductBase.borrower_types was added in https://github.com/open-contracting/credere-backend/commit/8c58d7a2d4929724c2a5ac813eeadc22fd900279 but ICreditProductBase was not updated.

`borrower_types` is part of `CreditProductInput` (see `creditProductSchema` in `OCPsettings`)

**Comment by jpmckinney** [comment]
Yes, but what about the other schema in `application.ts`? ICreditProduct (which extends ICreditProductUpdate, which extends ICreditProductBase) that is used in ILender, IApplication, IApplicationResponse, IApplicationCreditOptions.

**Comment by yolile** [comment]
We only need `borrower_types` in the OCP admin form as that field is only needed in the front end for creating credit products then the credit products are filtered in the back end and the field is never shown anywhere else.

**Comment by jpmckinney** [comment]
In principle, the API should not be returning data that the frontend does not need or use. FastAPI [recommends separate models for parsers, serializers and database tables](https://sqlmodel.tiangolo.com/tutorial/fastapi/multiple-models/). This is done in some cases but not all. In cases where a base table is reused across contexts, the field (like `borrower_types`) ends up being included where it's not intended. So, I'll just log this as an issue in the backend.
