### ISSUE TITLE
Edited fields: mark if they have been manually updated already

### ISSUE THREAD

**Issue by yolile** [open-contracting/credere-frontend#33]
For example, if OCP edits a field and then the FI reviews the application, they will see, for example:
![image](https://github.com/open-contracting/credere-frontend/assets/6834122/39e372bc-ab15-4e0f-b6fb-41d3f4871477)

There should be an indication that OCP already entered the field

**Comment by nahu** [comment]
Currently, if the data is not edited, it shows (Blank); if there is some data, it means someone has already revised it. You want to indicate that an OCP admin edited the data as an enhancement, right? How should this be displayed?

**Comment by yolile** [comment]
> You want to indicate that an OCP admin edited the data as an enhancement, right?

Yes

> How should this be displayed?

You can add a label saying, "Manually entered by [username] from OCP, (or by [username] from [FI name])"

**Comment by nahu** [comment]
In "More information" or this instead of the option of "+ Edit manually"?
