### ISSUE TITLE
Add Fathom Analytics

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/credere-frontend#76]
I don't think we configured any general analytics. If we use Fathom, I can:

* [x] add a new site and share the embed code
* [x] update https://docs.google.com/spreadsheets/d/1MMqid2qDto_9-MLD_qDppsqkQy_6OP-Uo-9dCgoxjSg/edit#gid=1480832278

**Comment by jpmckinney** [comment]
`<script src="https://cdn.usefathom.com/script.js" data-spa="auto" data-site="RPQMNYXX" defer data-excluded-domains="localhost,127.0.0.1,0.0.0.0"></script>`

**Comment by yolile** [comment]
from Slack @jpmckinney: 

> We can use Fathom to track clicked links by adding UTM parameters to the links: https://usefathom.com/docs/start/utms (edited)
